version: "3"
services:
  vote:
    build:
      context: .
      target: build
    working_dir: /src
    command: ["go", "run", "./..."]
    volumes:
      - type: bind
        source: .
        target: /src
    container_name: vote
    depends_on:
      - mongodb
    env_file:
      - path: .env
        required: false
    ports:
      - "127.0.0.1:8080:8080"

  mongodb:
    image: docker.io/mongo:4.4.26-focal
    container_name: mongodb
    command: "mongod --bind_ip 0.0.0.0"
    environment:
      - "MONGO_INITDB_DATABASE=vote"
      - "MONGO_INITDB_ROOT_USERNAME=vote"
      - "MONGO_INITDB_ROOT_PASSWORD=c1f66aac6b4fafbef3c659371b8a50ed"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - type: volume
        source: mongodb
        target: /data/db/

volumes:
  mongodb:
